apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: acute-bass-go 
  janus-idp.io/tekton: acute-bass-go
  backstage.io/kubernetes-id: acute-bass-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: acute-bass-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  