apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: acute-bass-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: acute-bass-go 
  name: acute-bass-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: acute-bass-go 
